# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170216_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('nigiri', 'Nigiri Pack'), ('hoso_maki', 'Hoso Maki Pack'), ('deka_maki', 'Deka Maki Pack'), ('nosé_maki', 'Nosé Maki Pack'), ('sushi', 'Sushi Pack'), ('platters', 'Platters'), ('misc', 'Miscellaneous')], default='misc', max_length=250),
            preserve_default=False,
        ),
    ]
